apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-portal
  description: An example of a Backstage application.
  annotations:
    'jenkins.io/job-full-name': pipeline-teste-backstage
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
